---
  - name: Load all images from location {{ docker_images_location }}
    docker_image:
      name: "{{ item.name }}"
      tag: "{{ item.tag }}"
      load_path: "{{ docker_images_location }}/{{ item.path }}"
    with_items:
      - { name: autolabjs/executionnode, tag: 0.5.0, path: execution_node.tar }
