---
- name: Enable UFW
  ufw:
    state: enabled
    logging: on

- name: Set the default incoming policy of UFW to deny
  ufw:
    direction: incoming
    policy: deny
    log: yes

- name: Set the default outgoing policy of UFW to allow
  ufw:
    direction: outgoing
    policy: allow

- name: Allow traffic for execution nodes from load balancer
  ufw:
    rule: allow
    proto: tcp
    src: "{{ lb_hostname }}"
    port: "{{ hostvars[item]['en_port'] }}"
    log: yes
    comment: "autolabjs"
  loop: "{{ groups['executionnodes'] }}"
